addSbtPlugin("org.typelevel" % "sbt-typelevel" % "0.7.7")
addSbtPlugin("org.typelevel" % "sbt-typelevel-site" % "0.7.7")
addSbtPlugin("org.scala-js" % "sbt-scalajs" % "1.18.2")
addSbtPlugin("org.scalameta" % "sbt-mdoc" % "2.6.4")
addSbtPlugin("org.scoverage" % "sbt-scoverage" % "2.3.1")
